# Generated by Django 2.2.2 on 2019-06-22 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silverstrike', '0008_auto_20190622_0952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'account_type', 'user')},
        ),
    ]
